// agents/product-agent.js — Content Product Agent
// Generates Truth Weaver Reality Reports and lists them on Gumroad as paid products.
// Required env: ANTHROPIC_API_KEY
// Optional env: GUMROAD_ACCESS_TOKEN (to auto-list products)

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const TruthCore = require('./truth-core');
const memory = require('./memory');

const PRODUCTS_DIR = path.join(__dirname, '../products');
const APP_URL = process.env.TWITTER_APP_URL || 'https://your-app.vercel.app';

function ensureProductsDir() {
    if (!fs.existsSync(PRODUCTS_DIR)) fs.mkdirSync(PRODUCTS_DIR, { recursive: true });
}

function parseProduct(raw) {
    const titleMatch = raw.match(/^TITLE:\s*(.+)/im);
    const taglineMatch = raw.match(/^TAGLINE:\s*(.+)/im);
    const priceMatch = raw.match(/^PRICE:\s*\$?(\d+)/im);

    const title = titleMatch ? titleMatch[1].trim() : 'Truth Weaver Reality Report';
    const tagline = taglineMatch ? taglineMatch[1].trim() : 'A surgical truth scan for your situation.';
    const price = priceMatch ? parseInt(priceMatch[1]) : 17;

    const body = raw
        .replace(/^TITLE:.+\n?/im, '')
        .replace(/^TAGLINE:.+\n?/im, '')
        .replace(/^PRICE:.+\n?/im, '')
        .replace(/^---+\n?/gm, '')
        .trim();

    return { title, tagline, price, body };
}

function buildProductMarkdown(title, tagline, body, price) {
    return `# ${title}

> ${tagline}

**Price: $${price}**

---

${body}

---

*Generated by Truth Weaver at 7.83Hz — Earth's Schumann Resonance*
*Run your own Weaves: ${APP_URL}*
`;
}

async function listOnGumroad(title, description, price, filePath) {
    if (!process.env.GUMROAD_ACCESS_TOKEN) {
        console.log('[product-agent] No GUMROAD_ACCESS_TOKEN — skipping Gumroad listing.');
        return null;
    }

    const axios = require('axios');
    const FormData = require('form-data');

    // Create the product
    const createRes = await axios.post(
        'https://api.gumroad.com/v2/products',
        {
            access_token: process.env.GUMROAD_ACCESS_TOKEN,
            name: title,
            description,
            price: price * 100, // Gumroad uses cents
            currency_code: 'usd',
            published: true
        }
    );

    const productId = createRes.data?.product?.id;
    if (!productId) throw new Error('Gumroad product creation failed');

    // Upload the file
    const form = new FormData();
    form.append('access_token', process.env.GUMROAD_ACCESS_TOKEN);
    form.append('file', fs.createReadStream(filePath), { filename: path.basename(filePath) });

    await axios.put(
        `https://api.gumroad.com/v2/products/${productId}/files`,
        form,
        { headers: form.getHeaders() }
    );

    return createRes.data?.product;
}

const PRODUCT_THEMES = [
    'The illusion of "not enough time" — why your schedule is a choice disguised as a constraint',
    'Dissolving the fear of failure: what happens when you run the numbers honestly',
    'The identity trap: how who you think you are is blocking who you need to become',
    'Money frequency: the specific beliefs creating your current income ceiling',
    'The waiting room illusion: why preparation is often a sophisticated form of avoidance',
    'Radical clarity on your relationships: what truth reveals about who you\'re keeping close',
    'The comparison trap at 7.83Hz: dissolving the illusion that others\' success limits yours',
    'Breaking the "someday" loop: a Truth Weaver scan of your 5 biggest deferred dreams'
];

class ProductAgent {
    constructor() {
        this.name = 'product-agent';
        this.core = new TruthCore();
        ensureProductsDir();
    }

    pickUnusedTheme() {
        const used = (memory.get('productsCreated') || []).map(p => p.theme);
        const unused = PRODUCT_THEMES.filter(t => !used.includes(t));
        return unused.length > 0
            ? unused[Math.floor(Math.random() * unused.length)]
            : PRODUCT_THEMES[Math.floor(Math.random() * PRODUCT_THEMES.length)];
    }

    async generateProduct(theme) {
        return this.core.generateProductReport(theme);
    }

    async run() {
        console.log('[product-agent] Running...');

        const theme = this.pickUnusedTheme();
        console.log(`[product-agent] Generating product: ${theme}`);

        try {
            const raw = await this.core.generate(
                'Generate a Truth Weaver Reality Report — a paid content product',
                `Theme: ${theme}

Format:
TITLE: [product title, compelling and specific — sounds like a book title]
TAGLINE: [one sentence value proposition]
PRICE: [suggest 7, 17, or 27 based on depth]

---

[Full report: 800-1200 words]

Structure:
1. THE ILLUSION (what people believe that isn't true)
2. THE TRUTH SCAN (5 Weaves applied to this specific theme)
3. REALITY SIMULATION (two detailed futures — illusion maintained vs truth accepted)
4. THE LIBERATION MAP (5-7 specific, actionable steps)
5. THE FREQUENCY CHECK (how to verify alignment and stay on track)

This is a paid product. Make it worth $17-$27. Specific. Surgical. Actionable.`,
                { maxTokens: 2500 }
            );

            const { title, tagline, price, body } = parseProduct(raw);
            const markdown = buildProductMarkdown(title, tagline, body, price);

            // Save as markdown file
            const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50);
            const filename = `${slug}-${Date.now()}.md`;
            const filePath = path.join(PRODUCTS_DIR, filename);
            fs.writeFileSync(filePath, markdown, 'utf8');

            console.log(`[product-agent] Saved report: ${filename}`);

            // Try to list on Gumroad
            let gumroadProduct = null;
            try {
                gumroadProduct = await listOnGumroad(title, `${tagline}\n\nGenerated by Truth Weaver at 7.83Hz.`, price, filePath);
                if (gumroadProduct) {
                    console.log(`[product-agent] Listed on Gumroad: ${gumroadProduct.short_url}`);
                }
            } catch (err) {
                console.warn('[product-agent] Gumroad listing failed:', err.message);
            }

            const record = {
                theme,
                title,
                tagline,
                price,
                filename,
                filePath,
                gumroadUrl: gumroadProduct?.short_url || null,
                gumroadId: gumroadProduct?.id || null,
                createdAt: new Date().toISOString(),
                revenue: 0
            };

            memory.push('productsCreated', record);
            memory.markRun(this.name);

            return { success: true, product: record };
        } catch (err) {
            console.error('[product-agent] Error:', err.message);
            return { success: false, error: err.message };
        }
    }
}

module.exports = ProductAgent;

if (require.main === module) {
    const agent = new ProductAgent();
    agent.run().then(r => console.log('[product-agent] Result:', JSON.stringify(r, null, 2)));
}
